/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * STSTester.java
 *
 * Created on Jun 5, 2012, 9:34:15 AM
 */
package stsdriver;

/**
 *
 * @author jim006
 */
public class STSTester extends javax.swing.JFrame {

    /** Creates new form STSTester */
    public STSTester() {
        initComponents();
        sts = new STSDriver("COM1");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSpectrum = new javax.swing.JButton();
        jbQuit = new javax.swing.JButton();
        jbSend2 = new javax.swing.JButton();
        jbGetTemperature = new javax.swing.JButton();
        jbGetTemp1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfAvgScans = new javax.swing.JTextField();
        jbSetAvgScans = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfIntegrationTime = new javax.swing.JTextField();
        jbSetIntegratonTime = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbSpectrum.setText("Send");
        jbSpectrum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSpectrumActionPerformed(evt);
            }
        });

        jbQuit.setText("Quit");
        jbQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitActionPerformed(evt);
            }
        });

        jbSend2.setText("Send2");
        jbSend2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSend2ActionPerformed(evt);
            }
        });

        jbGetTemperature.setText("Temperature");
        jbGetTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGetTemperatureActionPerformed(evt);
            }
        });

        jbGetTemp1.setText("Temperature 1");
        jbGetTemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGetTemp1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Average Scans");

        jtfAvgScans.setColumns(10);
        jtfAvgScans.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfAvgScans.setText("10");

        jbSetAvgScans.setText("Set");
        jbSetAvgScans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetAvgScansActionPerformed(evt);
            }
        });

        jLabel2.setText("Integration Time");

        jtfIntegrationTime.setColumns(10);
        jtfIntegrationTime.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtfIntegrationTime.setText("5000000");

        jbSetIntegratonTime.setText("Set");
        jbSetIntegratonTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSetIntegratonTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(jbQuit)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbGetTemp1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbGetTemperature)
                            .addComponent(jbSend2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSpectrum)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfAvgScans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIntegrationTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSetIntegratonTime)
                    .addComponent(jbSetAvgScans))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jbSend2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGetTemperature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSpectrum)
                        .addGap(27, 27, 27)))
                .addComponent(jbGetTemp1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfAvgScans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSetAvgScans))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfIntegrationTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSetIntegratonTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jbQuit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbQuitActionPerformed

    private void jbSpectrumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSpectrumActionPerformed
        sts.sendTest();
    }//GEN-LAST:event_jbSpectrumActionPerformed

    private void jbSend2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSend2ActionPerformed
        STSMessage msg = new STSMessage(STSMessage.MSG_GET_CORRECTED_SPECTRUM);
        sts.sendMessage(msg);
    }//GEN-LAST:event_jbSend2ActionPerformed

    private void jbGetTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGetTemperatureActionPerformed
        STSMessage msg = new STSMessage(STSMessage.MSG_GET_ALL_TEMPERATURE);
        sts.sendMessage(msg);
    }//GEN-LAST:event_jbGetTemperatureActionPerformed

    private void jbGetTemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGetTemp1ActionPerformed
        byte[] immediate_data = new byte[16];
        immediate_data[0] = 3;
        STSMessage msg = new STSMessage(STSMessage.MSG_GET_TEMPERATURE, immediate_data, 0);
        sts.sendMessage(msg);
    }//GEN-LAST:event_jbGetTemp1ActionPerformed

    private void jbSetAvgScansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetAvgScansActionPerformed
        sts.setScanAverage(Integer.parseInt(jtfAvgScans.getText()));
    }//GEN-LAST:event_jbSetAvgScansActionPerformed

    private void jbSetIntegratonTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSetIntegratonTimeActionPerformed
        sts.setIntegrationTime(Integer.parseInt(jtfIntegrationTime.getText()));
    }//GEN-LAST:event_jbSetIntegratonTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STSTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STSTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STSTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STSTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new STSTester().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbGetTemp1;
    private javax.swing.JButton jbGetTemperature;
    private javax.swing.JButton jbQuit;
    private javax.swing.JButton jbSend2;
    private javax.swing.JButton jbSetAvgScans;
    private javax.swing.JButton jbSetIntegratonTime;
    private javax.swing.JButton jbSpectrum;
    private javax.swing.JTextField jtfAvgScans;
    private javax.swing.JTextField jtfIntegrationTime;
    // End of variables declaration//GEN-END:variables
    STSDriver sts;
}
